export const filmsData = [
  {
    id: 1,
    title: "Tôi thấy hoa vàng trên cỏ xanh",
    engTitle: "Dear brother",
    img: "assets/images/Toithayhoavangtrencoxanh.jpg",
    type: "Tâm lý, tình cảm",
    director: "Victor Vũ",
    actors: "Thịnh Vinh, Trọng Khang, Thanh Mỹ, Lê Vinh,...",
    year: "2015",
    nation: "Việt Nam",
    info: "Tôi thấy hoa vàng trên cỏ xanh” là bộ phim chuyển thể từ quyển truyện dài cùng tên của nhà văn Nguyễn Nhật Ánh, từng tạo nên cơn sốt và đạt giải thưởng văn học ASEAN vào năm 2010. Chuyện phim là tuổi thơ nghèo khó của hai anh em Thiều và Tường ở một làng quê Việt thân thuộc và nên thơ. Là nơi đã chứng kiến những rung động đầu đời của cả hai, tình cảm gia đình, tình anh em yêu thương chân thành, cũng như những đố kỵ, ghen tuông và những nỗi đau trong veo trong quá trình trưởng thành. Dưới những khung hình tuyệt đẹp và giàu cảm xúc của đạo diễn Victor Vũ, “Tôi thấy hoa vàng trên cỏ xanh” sẽ là một “tấm vé” đưa người xem trở lại với tuổi thơ lắm ngọt ngào lẫn day dứt mà mỗi người đều đã từng trải qua.",
    time: "92",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/wHLpZycZNwE"
},
  {
    id: 2,
    title: "Em Là Bà Nội Của Anh",
    engTitle: "Sweet 20",
    img: "assets/images/emlabanoicuaanh.jpg",
    type: "Tâm lý, Hài hước",
    director: "Phan Gia Nhật Linh",
    actors: "Miu Lê, Ngô Kiến Huy, Hứa Vĩ Văn, NSND Thanh Nam,...",
    year: "2015",
    nation: "Việt Nam",
    info: "Chuyện phim xoay quanh bà Đại (NSƯT Minh Đức), bà già kiểu cách, khó tính, đặc biệt yêu thương cậu con trai độc nhất Quang (Đức Khuê) đang là giáo sư đại học. Nhưng tuổi xế chiều của bà không được yên ổn khi mâu thuẫn với con dâu (Hồng Ánh), với bạn bè, với quá khứ đầy sóng gió xưa kia cứ thế ập đến. Trong lúc quẫn bách nhất, phép màu đột ngột xảy đến, biến bà Đại trở thành cô gái trẻ trung tuổi đôi mươi. Không lãng phí cơ hội trời cho, bà quyết định tận dụng từng khoảnh khắc của “giấc mơ đẹp” để hoàn thành nhiều tâm nguyện còn dang dở. Cô gái Thanh Nga (Miu Lê) xinh đẹp xuất hiện, làm đảo lộn cuộc sống của cậu ca sĩ nhạc rock nổi loạn Ngô Trí Tùng (Ngô Kiến Huy) – vốn chính là cháu bà Đại, nhà sản xuất âm nhạc đẹp trai Mạnh Đức (Hứa Vĩ Văn) và cả ông bạn già tên Bé (NSƯT Thanh Nam) lỡ yêu sâu đậm bà Đại từ thuở trẻ.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/BGraUGKBAHk"
},
  {
    id: 3,
    title: "Em Chưa 18",
    engTitle: "Jailbait",
    img: "assets/images/emchua18.jpg",
    type: "Tình cảm, hài hước",
    director: "Lê Thanh Sơn",
    actors: "Kiều Minh Tuấn, Kaity Nguyễn, Will, Châu Bùi,...",
    year: "2017",
    nation: "Việt Nam",
    info: "Em Chưa 18 xoay quanh câu chuyện tình yêu, tình bạn, sự ganh đua giữa những người trẻ tuổi. Hoàng – tay chơi quan niệm “một lần rồi thôi” với mọi cô gái, bị dính vào mối quan hệ phức tạp không ngờ với Linh Đan - cô nàng ranh mãnh đang lên kế hoạch trả thù chàng bồ cũ Tony. Linh Đan đã làm gì để đạt được mục đích với Hoàng? Tony phải dùng chiêu nào để chống lại tất cả những đòn yêu này? Khi thời hạn hợp tác giữa Hoàng và Linh Đan kết thúc, trong cuộc đua này ai là người thắng - kẻ thua? Sau tất cả, Linh Đan liệu có tìm được hạnh phúc?",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/_affkHceSj4"
},
  {
    id: 4,
    title: "Ngày Mai Mai Cưới",
    engTitle: "Tomorrow, wedding tomorrow",
    img: "assets/images/ngaymaimaicuoi.jpg",
    type: "Hài hước",
    director: "Nguyễn Tấn Phước",
    actors: "Diệu Nhi, Vinh Râu, Thái Vũ, Huỳnh Phương,...",
    year: "2017",
    nation: "Việt Nam",
    info: "Ngày Mai Mai Cưới xoay quanh bốn người bạn chơi thân với nhau từ khi mới lọt lòng tại vùng biển Gò Công Đông. Trong bốn người có cô gái tên Mai (Diệu Nhi) như “lạc quẻ” giữa ba thằng bạn thân. Mai có ước mơ trở thành cảnh sát giao thông nhưng bị gia đình ép buộc theo học kế toán và lấy chồng cho hết ế. Anh chàng mắc tật cà lăm khi gặp chuyện căng thẳng Bền (Vinh Râu) nuôi mộng trở thành ca sĩ nhưng gia đình muốn anh theo nghề gia truyền cào nghêu. Còn Gừng (Thái Vũ) mong muốn làm nhà thám đại dương lại phải đi bỏ mối nước đá giúp gia đình. Mành (Huỳnh Phương) bị mù màu đỏ, có một ước mơ “nhỏ nhoi” trở thành tỉ phú đô la, trớ trêu thay gia đình lại muốn anh chàng đi tu. Mọi thứ càng trở nên rối rắm khi ba mẹ Mai (Trung Dân, Cát Phượng) ép con gái mau lấy chồng. Hàng loạt ứng viên sáng giá được ông bà chọn ra mắt Mai tạo nên nhiều chuyện “cười ra nước mắt”. Từ đây, hàng loạt tình huống dở khóc dở cười do ba mẹ Mai sắp đặt để con gái hết ế hứa hẹn sẽ mang đến những trận cười, những cú “twist” thú vị cho khán giả.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/oUL6GmlMy-8"
},
  {
    id: 5,
    title: "Cô Ba Sài Gòn",
    engTitle: "The tailor",
    img: "assets/images/cobasaigon.jpg",
    type: "Chính kịch",
    director: "Trần Bửu Lộc, Kay Nguyễn",
    actors: "Ninh Dương Lan Ngọc, NSND Hồng Vân, Diễm My, Ngô Thanh Vân,...",
    year: "2017",
    nation: "Việt Nam",
    info: "Cô Ba Sài Gòn – Năm 1969, nhà may Thanh Nữ là nhà may áo dài nổi tiếng nhất Sài Gòn. Gia đình này 9 đời đều may áo dài. Bà chủ Thanh Mai có hai cô con gái: cô con gái ruột Như Ý và cô con gái nuôi Thanh Loan. Thanh Loan thích may áo dài nhưng Như Ý lại thích thiết kế đồ Tây, vì cô cho rằng áo dài đã quá xưa và chỉ có một kiểu. Bà Thanh Mai kêu Như Ý hãy học cách may áo dài nhưng cô không quan tâm, cô chỉ thích thiết kế đồ Tây. Một hôm bà Thanh Mai lấy tấm vải quý của gia tộc ra may thành chiếc áo dài cực kỳ đẹp, rồi để bên dưới nhà. Như Ý thấy chiếc áo dài đẹp quá (có đính tên Như Ý trên áo) nên lấy mặc thử. Một điều kỳ lạ đã xảy ra, khi cô mặc chiếc áo dài vào, miếng ngọc trên chiếc áo đã cuốn cô vào dòng thời gian, đưa cô đến năm 2017.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/E_Y4z8gJjvM"
},
  {
    id: 6,
    title: "Mẹ Chồng",
    engTitle: "Mother in law",
    img: "assets/images/mechong.jpg",
    type: "Chính kịch",
    director: "Lê Hoàng",
    actors: "Thanh Hằng, Diễm My, Lan Khuê, Ngọc Quyên,...",
    year: "2017",
    nation: "Việt Nam",
    info: "Mẹ chồng là một câu chuyện xảy ra ở bối cảnh giả định mang tên Đại Điền vào những năm 1945 - 1950, xoay quanh cuộc đời cô Ba Trân (Thanh Hằng), một người phụ nữ Nam Bộ chịu nhiều ảnh hưởng của nền giáo dục Nho giáo. Từ khi về làm dâu, Ba Trân luôn phải chịu nhiều bất hạnh với những quy củ hà khắc từ gia đình nhà chồng. Ngỡ tưởng, những bi thương từng nếm trải sẽ khiến Ba Trân trở nên vị tha và nhân hậu hơn với con dâu mình. Thế nhưng, do sức ép của việc gìn giữ và duy trì nền nếp dòng họ, cô lại tiếp tục lặp lại con đường nhân bản bi kịch của mình lên những người phụ nữ khác khi cô trở thành mẹ chồng.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/LBrBwtACGeU"
},
  {
    id: 7,
    title: "Nắng",
    engTitle: "Sunny",
    img: "assets/images/nang.jpg",
    type: "Tình cảm, tâm lý",
    director: "Đồng Đăng Giao",
    actors: "Kim Thư, Thu Trang, Trấn Thành, Kiều Minh Tuấn,...",
    year: "2016",
    nation: "Việt Nam",
    info: "Bộ phim Nắng khắc họa tình mẫu tử thiêng liêng của người mẹ thiểu năng tên Mưa với đứa con gái bé bỏng tên Nắng. Hai mẹ con Mưa, Nắng là những người ở đáy cùng của xã hội. Họ vất vả mưu sinh bằng nghề bán vé số, lượm ve chai. Trong khi người mẹ khù khờ, ngờ nghệch, cô gái nhỏ của chị lại lanh lợi, thông minh. Những tình cảm yêu thương, quấn quýt của hai mẹ con dành cho nhau lồng trong bối cảnh cuộc sống đời thường mang đến góc nhìn dễ thương, dung dị.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/tyaq_lOwqmg"
},
  {
    id: 8,
    title: "Tháng Năm Rực Rỡ",
    engTitle: "Brilliant May",
    img: "assets/images/thangnamrucro.jpg",
    type: "Hài hước, tâm lý",
    director: "Nguyễn Quang Dũng",
    actors: "Anh Thư, Mỹ Duyên, Hồng Ánh, Thanh Hằng,...",
    year: "2018",
    nation: "Việt Nam",
    info: "THÁNG NĂM RỰC RỠ là câu chuyện về tình bạn, về thời tuổi trẻ cuồng nhiệt của một nhóm bạn gái thời trung học. Bộ phim là hành trình đi tìm lại những ký ức thanh xuân của Hiểu Phương (Hồng Ánh) và nhóm nữ quái Ngựa Hoang. Tình cờ gặp lại người bạn cũ Mỹ Dung (Thanh Hằng) và cũng là trưởng nhóm Ngựa Hoang, Hiểu Phương đau xót khi biết bạn đang mắc bệnh hiểm nghèo. Để thực hiện tâm nguyện của bạn thân, Hiểu Phương quyết tâm tìm lại các thành viên của nhóm Ngựa Hoang. Hành trình đi tìm những người bạn cũ cũng chính là hành trình để Hiểu Phương trở về với những “THÁNG NĂM RỰC RỠ” của cuộc đời mình.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/RyQeBPpZqdY"  
},
  {
    id: 9,
    title: "Tèo em",
    engTitle: "Teo Em",
    img: "assets/images/teoem.jpg",
    type: "Hài hước",
    director: "Charlie Nguyễn",
    actors: "Thái Hòa, Johny Nguyễn, Lan Ngọc,...",
    year: "2015",
    nation: "Việt Nam",
    info: "Johnny Trí Nguyễn và Thái Hòa vào vai hai anh em Tí, Tèo có cuộc sống và tính cách khác nhau. Một người lanh lợi, lịch lãm; kẻ còn lại thì cù lần, ngây ngô. Họ buộc phải đi cùng nhau trên một chuyến xe về thị xã Sa Đéc, chạy đua với thời gian nhằm cứu vãn một mối tình. Trên đường đi, sự khác biệt làm nảy sinh xung đột và dẫn tới những câu chuyện dở khóc dở cười.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/oRvzM1eX5ow" 
},
];
